### ISSUE TITLE
Launch two solver in a row make the second one crash

### ISSUE THREAD

**Issue by adrdv** [optapy/optapy#133]
Hello,
I have a problem that I split into two parts.
When I run a first solver with the first part, then at the end a second solver with the second part. The second one crashes systematically with the error : java.lang.RuntimeException: java.lang.IllegalArgumentException: OptaPySolver does not exist in global scope
The strangest thing is that if I change the order of my problems it is always the one I put first that works. 
As if running the solver twice would cause it to crash.
Is this a known bug ?

**Comment by Christopher-Chianelli** [comment]
Can you post what code you are running so I can try to replicate it? You should be able to solve multiple time, like so:

```
solver = solver_factory_create(solver_config).buildSolver()
solution = solver.solve(generate_problem())
solver.solve(solution)

# OR

solver_1 = solver_factory_create(solver_config_1).buildSolver()
solution_1 = solver_1.solve(generate_problem())


solver_2 = solver_factory_create(solver_config_2).buildSolver()
solution_2 = solver_2.solve(solution_1)
```

**Comment by adrdv** [comment]
Hello, 
Thanks for your answer. 
I have found the issue who came from a constraint that was using a macro but can't have access since it was outside the scope. 
I didn't understand why it works the first time but I have fix the issue. 
But I think that the error displayed were not very helpful, for example I did not know what line causes trouble.
