### ISSUE TITLE
Optaplanner design pattern diagrams

### ISSUE THREAD

**Issue by PeterPirog** [optapy/optapy#141]
What software is used to create this optaplanner diagrams:
[https://www.optaplanner.org/docs/optaplanner/latest/_images/design-patterns/employeeShiftRosteringModelingGuideA.png](https://www.optaplanner.org/docs/optaplanner/latest/_images/design-patterns/employeeShiftRosteringModelingGuideA.png)

**Comment by Christopher-Chianelli** [comment]
Inkscrape (https://inkscape.org/), it is first drawn as a SVG, then exported as a PNG.

**Comment by PeterPirog** [comment]
@Christopher-Chianelli Thank You for the aswer.
