### ISSUE TITLE
Implementing Min-Max Tutor Assignment Constraints in OptaPy

### ISSUE THREAD

**Issue by muhammedrinshid** [optapy/optapy#183]
I'm working on an educational scheduling project using OptaPy and need help implementing a constraint to control the number of lessons assigned to each tutor within a specified range.
Problem Description

- **Each tutor should be assigned to at least X lessons (minimum).
- No tutor should be assigned more than Y lessons (maximum).
- These limits may vary for different tutors based on their availability and workload capacity.**

Current Implementation
Here's a simplified version of our current Lesson class:
`pythonCopyfrom optapy import planning_entity, planning_variable
`
```
@planning_entity
class Lesson:
    def __init__(self, id, subject, available_teachers):
        self.id = id
        self.subject = subject
        self.available_teachers = available_teachers
        self._allotted_teacher = None

    @planning_variable(Tutor, value_range_provider_refs=['teacherRange'])
    def get_allotted_teacher(self):
        return self._allotted_teacher

    def set_allotted_teacher(self, new_teacher):
        self._allotted_teacher = new_teacher
```
Questions

1. What's the recommended approach in OptaPy to implement min-max assignment constraints?
2. Are there any built-in constraint types or score calculators we could use for this?
3. If a custom implementation is needed, could you provide some guidance or example code?
4. Are there any performance considerations we should be aware of?

What I've Tried
I've considered using a custom score calculator to count assignments and penalize violations, but I'm not sure if this is the most efficient approach or if there's a better way built into OptaPy.
Any help or guidance would be greatly appreciated. Thank you!

**Comment by Christopher-Chianelli** [comment]
I recommend you use to [Timefold Solver for Python](https://pypi.org/project/timefold/) instead (Timefold is the continuation of OptaPlanner/OptaPy by the original OptaPlanner team). Nevertheless, the advice below applies both to OptaPy and Timefold:

1. The recommend approach is to count assignments and penalize violations (using the violation amount in the penalty function)
2. There are no built-in constraints currently; you could use `ConstraintCollectors.count`.
3. An example implementation would look like this in Timefold:

```python
from timefold.solver.domain import *
from timefold.solver.score import *
from typing import Annotated
from dataclasses import dataclass, field

@dataclass
class Tutor:
    name: str
    minimum_lessons_assigned: int
    maximum_lessons_assigned: int


@planning_entity
@dataclass
class Lesson:
    id: str
    subject: str
    allotted_teacher: Annotated[Tutor | None, PlanningVariable] = field(default=None)


@planning_solution
@dataclass
class Timetable:
    tutors: Annotated[list[Tutor], ProblemFactCollectionProperty, ValueRangeProvider]
    lessons: Annotated[list[Lesson], PlanningEntityCollectionProperty]
    score: Annotated[HardSoftScore | None, PlanningScore] = field(default=None)


@constraint_provider
def timetabling_constraints(constraint_factory: ConstraintFactory):
    return [
        constraint_factory.for_each(Lesson)
            .group_by(lambda lesson: lesson.allotted_teacher, ConstraintCollectors.count())
            # A tutor without any lessons would not be grouped, so we need to add all tutors without any lessons
            # and give them a count of 0
            .complement(Tutor, lambda tutor: 0)
            .filter(lambda tutor, count: count < tutor.minimum_lessons_assigned)
            .penalize(HardSoftScore.ONE_HARD, lambda tutor, count: tutor.minimum_lessons_assigned - count)
            .as_constraint('Minimum assigned lesson violation for tutor'),

        constraint_factory.for_each(Lesson)
            .group_by(lambda lesson: lesson.allotted_teacher, ConstraintCollectors.count())
            .filter(lambda tutor, count: count > tutor.maximum_lessons_assigned)
            .penalize(HardSoftScore.ONE_HARD, lambda tutor, count: count - tutor.maximum_lessons_assigned)
            .as_constraint('Maximum assigned lesson violation for tutor')
    ]
```

4.. For this given constraint, no, but in general, see [this guide](https://docs.timefold.ai/timefold-solver/latest/constraints-and-score/performance).
