### ISSUE TITLE
School timetabling quickstart (code/readme/blog) should use snake_case for methods/variables (not camelCase)

### ISSUE THREAD

**Issue by ge0ffrey** [optapy/optapy#22]
![image](https://user-images.githubusercontent.com/176880/136347859-aad8356e-d51d-4af4-8fe5-4145cea66112.png)

The end goal is that all OptaPlanner public APIs are Python-natural (= snake_case) in OptaPy's public APIs.

**Comment by Christopher-Chianelli** [comment]
Huh, thought the comment would automatically close this issue after it was merged; guess not. Closing (was fixed in #25).
