### ISSUE TITLE
Suggestion: beware of default mutable args

### ISSUE THREAD

**Issue by fjsj** [optapy/optapy#24]
Hi, I'm not sure this really causes an issue on this library, but I see you do:
```python
@planning_solution
class TimeTable:
    def __init__(self, timeslotList=[], roomList=[], lessonList=[], score=None):
        ...
```

The use of `timeslotList=[], roomList=[], lessonList=[]` may be problematic since `[]` is mutable. Please check https://florimond.dev/en/posts/2018/08/python-mutable-defaults-are-the-source-of-all-evil/

**Comment by Christopher-Chianelli** [comment]
Should probably change the default in the example to None. It should not cause an issue if user code uses it; all fields are overwritten with clones (and the collections are not touched). The library itself does not use mutable default arguments.
