### ISSUE TITLE
Make the use of get_class() for ConstraintFactory methods obsolete

### ISSUE THREAD

**Issue by ge0ffrey** [optapy/optapy#26]
Allow this code
```
# Constraint Factory takes Java Classes, not Python Classes
LessonClass = get_class(Lesson)

def room_conflict(constraint_factory):
    # A room can accommodate at most one lesson at the same time.
    return constraint_factory \
            .from_(LessonClass) \
            ...
```
to run like this:
```
def room_conflict(constraint_factory):
    # A room can accommodate at most one lesson at the same time.
    return constraint_factory \
            .from_(Lesson) \
            ...
```
(Feel free to only do this for forEach() once that exists, instead of from_())

Proposals:

A) Read up about AOT (aspect oriënted programming) - it might be possible to do apply a AOT-like rule on all java to python api's that replace any Java API method `foo(JavaClass, ...)` with `foo(PythonClass x, ...) { foo(get_class(x, ...) }`. Not sure if JPype supports anything AOT like, but it would be a great feature request :)

B) Meanwhile, it's probably much more practical to just do this specifically for all ConstraintFactory from methods, there are not that many.

**Comment by Christopher-Chianelli** [comment]
Update: https://github.com/jpype-project/jpype/issues/1008 is resolved; once the next JPype version is released to PyPI I'll be able to close this issue
